//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]
        ///&quot;EnableHttp1_1&quot;=dword:00000001
        ///&quot;WarnonZoneCrossing&quot;=dword:00000000
        ///&quot;ProxyEnable&quot;=dword:00000000
        ///&quot;AutoConfigURL&quot;=&quot;http://proxy/wpad.dat&quot;
        ///
        ///[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections]
        ///&quot;DefaultConnectionSettings&quot;=hex:46,00,00,00,4d,00,00,00,05,00,00,00,1f,00,00,\
        ///  00,6f,63,74,72,6f,6c,66,2d,67,77,2e,69,6e,74,2e,72,6f,6c,66,63,6f,72,70,2e [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ARMS_Fix_reg {
            get {
                return ResourceManager.GetString("ARMS_Fix_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///NET USE B: /DELETE
        ///NET USE B: \\int.rolfcorp.ru\sfc /persistent:no &gt;nul.
        /// </summary>
        public static string B_Drive_bat {
            get {
                return ResourceManager.GetString("B_Drive_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title temp
        ///
        ///DEL /F /S /Q &quot;%USERPROFILE%\Local Settings\Temporary Internet Files\*&quot;
        ///DEL /F /S /Q &quot;%USERPROFILE%\Local Settings\Temp\*&quot;
        ///DEL /F /S /Q &quot;%USERPROFILE%\Recent\*&quot;
        ///DEL /F /S /Q &quot;%USERPROFILE%\Cookies\*&quot;
        ///DEL /F /S /Q &quot;c:\WINDOWS\Temp\*&quot;
        ///DEL /F /S /Q &quot;c:\temp\*&quot;
        ///DEL /F /S /Q &quot;c:\WINDOWS\Prefetch\*&quot;
        ///DEL /F /S /Q &quot;C:\WINDOWS\system32\config\systemprofile\Local Settings\Temporary Internet Files\*&quot;
        ///DEL /F /S /Q &quot;C:\WINDOWS\system32\config\systemprofile\Local Settings\Temp\*&quot;
        ///DEL /F /S /Q &quot;%USER [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Clear_temps_cmd {
            get {
                return ResourceManager.GetString("Clear_temps_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON {
            get {
                object obj = ResourceManager.GetObject("ICON", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 205.204.193.0/24 Черная Грязь
        ///205.204.207.0/24 ХОЛДИНГ
        ///192.168.117.0/24 ул. Алтуфьевское шоссе, д.31, строение 7, РОЛЬФ-ХОЛДИНГ
        ///192.168.118.0/24 ул. Алтуфьевское шоссе, д.31, строение 7, РОЛЬФ-ХОЛДИНГ
        ///192.168.119.0/24 ул. Алтуфьевское шоссе, д.31, строение 7, РОЛЬФ-ХОЛДИНГ
        ///192.168.210.0/24 *ул. Алтуфьевское шоссе, д.31, строение 1, РОЛЬФ-ХОЛДИНГ -  серверы
        ///192.168.153.0/24 *Сеть между центральным коммутатором и ISA-серверами
        ///205.204.192.0/24 *сеть в РАЦМ для подключения сервера по проекту Mazda
        ///172. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Subnets_19_03_2022 {
            get {
                return ResourceManager.GetString("Subnets_19_03_2022", resourceCulture);
            }
        }
    }
}
